export default {
    apiurl: (process.env.NODE_ENV === 'development') ? "http://cspi-ems-api.localhost.com/" : "http://emsapi.cherrypiksoftware.com/",
    authApis: {
        login: "api/auth/login",
        logout: "api/auth/logout",
        refreshToken: "api/auth/refresh",
    },
    apis: {
        userList: "api/users",
        authUser: "api/users/me",
        userInTime: "api/emp/in-time",
        userOutTime: "api/emp/out-time",
        getPermission: "api/permission",
        createPermission: "api/permission",
        updatePermission: "api/permission/",
        deletePermission: "api/permission/remove/",
        getRole: "api/role",
        createRole: "api/role",
        deleteRole: "api/role/remove/",
        deleteUser: "api/users/remove/",
        updateRole: "api/role/",
        updateImg: "api/upload",
        deleteImg: "api/remove-file",
        createUser: "api/users/create",
        editUser: "api/users/update/",
        singleUser: "api/users/",
        dureTime: "api/emp/totalDurationTime",
        holidayLeave: "api/holiday-leave",
        removeLeave: "api/holiday-leave/",
        eidtLeave:"api/holiday-leave/",
        singleLeave:"api/holiday-leave/",
        createTicket:"api/leave", 
    }
};